---
title: "Restructure"
author: "PRIYAM"
date: "2023-01-03"
output:
  word_document: default
  html_document: default
---

```{r}
#Libaries used in Project
library(tidyverse)
library(readxl)
library(stargazer)
library(magrittr)
library(haven)
library(plm)
library(ggplot2)
library(dplyr)
library(VGAM)
library(car)
library(censReg)
library(factoextra)
library(writexl)
library(Rserve)
library(scales)
library(pastecs)
library(panelr)
library(tidyverse)
```


```{r}
#Adding Data

df <- read_excel("C:/Users/91910/Desktop/Me MaRio/Papers/Subcontracting & Innovation/Data 2/Main Data Panel.xlsx", 
    sheet = "Sheet1")

```


```{r}
#Adding NIC 2 digit Column 
df$NIC2 <- substr(df$`NIC code`, 1, 2)
```


```{r}
#Changing the variable names to make them non-unique
names(df)[names(df) == "Year2"] <- "Year"
names(df)[names(df) == "Year13"] <- "Year"
names(df)[names(df) == "Year24"] <- "Year"
names(df)[names(df) == "Year35"] <- "Year"
names(df)[names(df) == "Year46"] <- "Year"
names(df)[names(df) == "Year57"] <- "Year"
names(df)[names(df) == "Year68"] <- "Year"
names(df)[names(df) == "Year79"] <- "Year"
names(df)[names(df) == "Year90"] <- "Year"
names(df)[names(df) == "Year101"] <- "Year"
names(df)[names(df) == "Year112"] <- "Year"


names(df)[names(df) == "Job-work income"] <- "SUB"
names(df)[names(df) == "Job-work income3"] <- "SUB"
names(df)[names(df) == "Job-work income14"] <- "SUB"
names(df)[names(df) == "Job-work income25"] <- "SUB"
names(df)[names(df) == "Job-work income36"] <- "SUB"
names(df)[names(df) == "Job-work income47"] <- "SUB"
names(df)[names(df) == "Job-work income58"] <- "SUB"
names(df)[names(df) == "Job-work income69"] <- "SUB"
names(df)[names(df) == "Job-work income80"] <- "SUB"
names(df)[names(df) == "Job-work income91"] <- "SUB"
names(df)[names(df) == "Job-work income102"] <- "SUB"
names(df)[names(df) == "Job-work income113"] <- "SUB"

names(df)[names(df) == "Profit after tax"] <- "PAT"
names(df)[names(df) == "Profit after tax4"] <- "PAT"
names(df)[names(df) == "Profit after tax15"] <- "PAT"
names(df)[names(df) == "Profit after tax26"] <- "PAT"
names(df)[names(df) == "Profit after tax37"] <- "PAT"
names(df)[names(df) == "Profit after tax48"] <- "PAT"
names(df)[names(df) == "Profit after tax59"] <- "PAT"
names(df)[names(df) == "Profit after tax70"] <- "PAT"
names(df)[names(df) == "Profit after tax81"] <- "PAT"
names(df)[names(df) == "Profit after tax92"] <- "PAT"
names(df)[names(df) == "Profit after tax103"] <- "PAT"
names(df)[names(df) == "Profit after tax114"] <- "PAT"

names(df)[names(df) == "Research & development expenses - current account"] <- "R&D"
names(df)[names(df) == "Research & development expenses - current account5"] <- "R&D"
names(df)[names(df) == "Research & development expenses - current account16"] <- "R&D"
names(df)[names(df) == "Research & development expenses - current account27"] <- "R&D"
names(df)[names(df) == "Research & development expenses - current account38"] <- "R&D"
names(df)[names(df) == "Research & development expenses - current account49"] <- "R&D"
names(df)[names(df) == "Research & development expenses - current account60"] <- "R&D"
names(df)[names(df) == "Research & development expenses - current account71"] <- "R&D"
names(df)[names(df) == "Research & development expenses - current account82"] <- "R&D"
names(df)[names(df) == "Research & development expenses - current account93"] <- "R&D"
names(df)[names(df) == "Research & development expenses - current account104"] <- "R&D"
names(df)[names(df) == "Research & development expenses - current account115"] <- "R&D"

names(df)[names(df) == "Net sales6"] <- "Net sales"
names(df)[names(df) == "Net sales17"] <- "Net sales"
names(df)[names(df) == "Net sales28"] <- "Net sales"
names(df)[names(df) == "Net sales39"] <- "Net sales"
names(df)[names(df) == "Net sales50"] <- "Net sales"
names(df)[names(df) == "Net sales61"] <- "Net sales"
names(df)[names(df) == "Net sales72"] <- "Net sales"
names(df)[names(df) == "Net sales83"] <- "Net sales"
names(df)[names(df) == "Net sales94"] <- "Net sales"
names(df)[names(df) == "Net sales105"] <- "Net sales"
names(df)[names(df) == "Net sales116"] <- "Net sales"

names(df)[names(df) == "Net plant and machinery"] <- "NPM"
names(df)[names(df) == "Net plant and machinery7"] <- "NPM"
names(df)[names(df) == "Net plant and machinery18"] <- "NPM"
names(df)[names(df) == "Net plant and machinery29"] <- "NPM"
names(df)[names(df) == "Net plant and machinery40"] <- "NPM"
names(df)[names(df) == "Net plant and machinery51"] <- "NPM"
names(df)[names(df) == "Net plant and machinery62"] <- "NPM"
names(df)[names(df) == "Net plant and machinery73"] <- "NPM"
names(df)[names(df) == "Net plant and machinery84"] <- "NPM"
names(df)[names(df) == "Net plant and machinery95"] <- "NPM"
names(df)[names(df) == "Net plant and machinery106"] <- "NPM"
names(df)[names(df) == "Net plant and machinery117"] <- "NPM"

names(df)[names(df) == "Salaries, wages, bonus, ex gratia pf & gratuities paid"] <- "Sal&Wag"
names(df)[names(df) == "Salaries, wages, bonus, ex gratia pf & gratuities paid8"] <- "Sal&Wag"
names(df)[names(df) == "Salaries, wages, bonus, ex gratia pf & gratuities paid19"] <- "Sal&Wag"
names(df)[names(df) == "Salaries, wages, bonus, ex gratia pf & gratuities paid30"] <- "Sal&Wag"
names(df)[names(df) == "Salaries, wages, bonus, ex gratia pf & gratuities paid41"] <- "Sal&Wag"
names(df)[names(df) == "Salaries, wages, bonus, ex gratia pf & gratuities paid52"] <- "Sal&Wag"
names(df)[names(df) == "Salaries, wages, bonus, ex gratia pf & gratuities paid63"] <- "Sal&Wag"
names(df)[names(df) == "Salaries, wages, bonus, ex gratia pf & gratuities paid74"] <- "Sal&Wag"
names(df)[names(df) == "Salaries, wages, bonus, ex gratia pf & gratuities paid85"] <- "Sal&Wag"
names(df)[names(df) == "Salaries, wages, bonus, ex gratia pf & gratuities paid96"] <- "Sal&Wag"
names(df)[names(df) == "Salaries, wages, bonus, ex gratia pf & gratuities paid107"] <- "Sal&Wag"
names(df)[names(df) == "Salaries, wages, bonus, ex gratia pf & gratuities paid118"] <- "Sal&Wag"

names(df)[names(df) == "Technical know-how fees and technical service fees"] <- "TK"
names(df)[names(df) == "Technical know-how fees and technical service fees9"] <- "TK"
names(df)[names(df) == "Technical know-how fees and technical service fees20"] <- "TK"
names(df)[names(df) == "Technical know-how fees and technical service fees31"] <- "TK"
names(df)[names(df) == "Technical know-how fees and technical service fees42"] <- "TK"
names(df)[names(df) == "Technical know-how fees and technical service fees53"] <- "TK"
names(df)[names(df) == "Technical know-how fees and technical service fees64"] <- "TK"
names(df)[names(df) == "Technical know-how fees and technical service fees75"] <- "TK"
names(df)[names(df) == "Technical know-how fees and technical service fees86"] <- "TK"
names(df)[names(df) == "Technical know-how fees and technical service fees97"] <- "TK"
names(df)[names(df) == "Technical know-how fees and technical service fees108"] <- "TK"
names(df)[names(df) == "Technical know-how fees and technical service fees119"] <- "TK"

names(df)[names(df) == "Company Name"] <- "CC"
names(df)[names(df) == "NIC code"] <- "NIC"
```


```{r}
#Converting new panel data using just the companies as the index 
#The lines of code given below are for making the data and making the data available as csv format. 
E3<-pdata.frame(df, index=("CC"), drop.index=TRUE, row.names=TRUE)
 write.csv(E3, file = "DATA.csv")
 
 
#This is the data that converts the data into longitudinal data structure 
E3.2<-read.csv("DATA.csv")
str(E3.2)
pnl<- long_panel(E3.2, prefix = ".", begin = 1, end = 10, id = "X", as_panel_data = T)
```


```{r}
#Calculating Intensity
pnl$Si = (pnl$SUB / pnl$Net.sales) * 100 
pnl$Ri = (pnl$R.D / pnl$Net.sales) * 100
pnl$Pi = (pnl$PAT / pnl$Net.sales) * 100
pnl$Ti = (pnl$TK / pnl$Net.sales) * 100
pnl$NPMi = (pnl$NPM / pnl$Net.sales)  * 100
write.csv(pnl, file = "panel.csv")
```


```{r}
#Creating panel NIC Sets

pnl_10<-subset(pnl, substr(pnl$NIC, 1, 2) == 10)
pnl_11<-subset(pnl, substr(pnl$NIC, 1, 2) == 11)
pnl_12<-subset(pnl, substr(pnl$NIC, 1, 2) == 12)
pnl_13<-subset(pnl, substr(pnl$NIC, 1, 2) == 13)
pnl_14<-subset(pnl, substr(pnl$NIC, 1, 2) == 14)
pnl_15<-subset(pnl, substr(pnl$NIC, 1, 2) == 15)
pnl_16<-subset(pnl, substr(pnl$NIC, 1, 2) == 16)
pnl_17<-subset(pnl, substr(pnl$NIC, 1, 2) == 17)
pnl_18<-subset(pnl, substr(pnl$NIC, 1, 2) == 18)
pnl_19<-subset(pnl, substr(pnl$NIC, 1, 2) == 19)
pnl_20<-subset(pnl, substr(pnl$NIC, 1, 2) == 20)
pnl_21<-subset(pnl, substr(pnl$NIC, 1, 2) == 21)
pnl_22<-subset(pnl, substr(pnl$NIC, 1, 2) == 22)
pnl_23<-subset(pnl, substr(pnl$NIC, 1, 2) == 23)
pnl_24<-subset(pnl, substr(pnl$NIC, 1, 2) == 24)
pnl_25<-subset(pnl, substr(pnl$NIC, 1, 2) == 25)
pnl_26<-subset(pnl, substr(pnl$NIC, 1, 2) == 26)
pnl_27<-subset(pnl, substr(pnl$NIC, 1, 2) == 27)
pnl_28<-subset(pnl, substr(pnl$NIC, 1, 2) == 28)
pnl_29<-subset(pnl, substr(pnl$NIC, 1, 2) == 29)
pnl_30<-subset(pnl, substr(pnl$NIC, 1, 2) == 30)
pnl_31<-subset(pnl, substr(pnl$NIC, 1, 2) == 31)
pnl_32<-subset(pnl, substr(pnl$NIC, 1, 2) == 32)
pnl_33<-subset(pnl, substr(pnl$NIC, 1, 2) == 33)
```

```{r}
# Checking for missing values
sum(is.na(pnl[,c("Ri","Si","Pi","Net.sales")]))

is.numeric("Ri")
is.numeric("Si")
is.numeric("Pi")
is.numeric("Net.sales")

# Removing missing values
pnl_complete = na.omit(pnl[,c("Ri","Si","Pi","Net.sales")])

# Calculating the variance-covariance matrix
varcov = cov(pnl_complete)
varcov
```


```{r}
# create a model for 
model <- lm(Ri ~ Si + Pi + Net.sales, data = pnl)

# calculate the VIF values
vif <- vif(model)
vif
```


```{r}
##NIC 2 digit code grouped by OECD classification of manufacturing industry 

#Food, Beverages, and Tobacco
G1 <- subset(pnl, NIC2 %in% c(10,11, 12))

#Textiles, Clothing, Leather, and Footwear
G2 <- subset(pnl, NIC2 %in% c(13,14, 15))

#Wood, Paper, Printing, and Publishing
G3 <- subset(pnl, NIC2 %in% c(16,17, 18))

#Chemicals and Chemical Products
G4 <- subset(pnl, NIC2 %in% c(20))

#Rubber, Plastic, and Non-Metallic Mineral Products
G5 <- subset(pnl, NIC2 %in% c(21,22))

#Basic Metals and Fabricated Metal Products
G6 <- subset(pnl, NIC2 %in% c(23,24))

#Machinery and Equipment
G7 <- subset(pnl, NIC2 %in% c(25,26,27,28,29))

#Miscellaneous Manufacturing
G8 <- subset(pnl, NIC2 %in% c(19,32,30,31))
```


```{r}
#Running the RegresSion Models with the new data structure. 

###FE MODEL

grun.fe <- plm(Ri ~ Si + Pi  + Net.sales , data = pnl, model = "within")
summary(grun.fe) 
nobs(grun.fe)

###RANDOM MODEL
grun.re2 <- plm(Ri ~ Si + Pi +  Net.sales , data = pnl, model = "random")
summary(grun.re2)
nobs(grun.re2)

stargazer::stargazer(grun.fe, grun.re2,  type = "text")

###Hausman test
## If p-value is < 0.05 then use fixed effects
phtest(grun.fe, grun.re2)
```

```{r}
#Running the Regression Models with the new data structure. 

###FE MODEL

grun.fe1 <- plm(Ri ~ Si + Pi  + Net.sales + Si*Pi, data = pnl, model = "within")
summary(grun.fe1) 
nobs(grun.fe1)

###RANDOM MODEL
grun.re21 <- plm(Ri ~ Si + Pi +  Net.sales  + Si*Pi , data = pnl, model = "random")
summary(grun.re21)
nobs(grun.re21)

stargazer::stargazer(grun.fe1, grun.re21,  type = "text")

###Hausman test
## If p-value is < 0.05 then use fixed effects
phtest(grun.fe1, grun.re21)
```

```{r}
###Tobit Model
panelResult <- censReg( Ri ~ Si + Pi + Net.sales, data = pnl)

summary (panelResult)

panelResult1 <- censReg( Ri ~ Si + Pi + Net.sales + Si*Pi, data = pnl)

summary (panelResult1)

stargazer::stargazer(panelResult, panelResult1,  type = "text")


```


```{r}
###NIC Panel | Random effect
Reg_10a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_10, model = "within")
summary(Reg_10a)

Reg_11a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_11, model = "within")
summary(Reg_11a)

Reg_12a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_12, model = "within")
summary(Reg_12a)

Reg_13a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_13, model = "within")
summary(Reg_13a)

Reg_14a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_14, model = "within")
summary(Reg_14a)

#Reg_15a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_15, model = "within")
#summary(Reg_15a)

Reg_16a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_16, model = "within")
summary(Reg_16a)

Reg_17a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_17, model = "within")
summary(Reg_17a)

Reg_18a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_18, model = "within")
summary(Reg_18a)

Reg_19a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_19, model = "within")
summary(Reg_19a)

Reg_20a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_20, model = "within")
summary(Reg_20a)

Reg_21a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_21, model = "within")
summary(Reg_21a)

Reg_22a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_22, model = "within")
summary(Reg_22a)

Reg_23a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_23, model = "within")
summary(Reg_23a)

Reg_24a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_24, model = "within")
summary(Reg_24a)

Reg_25a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_25, model = "within")
summary(Reg_25a)

Reg_26a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_26, model = "within")
summary(Reg_26a)

Reg_27a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_27, model = "within")
summary(Reg_27a)

Reg_28a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_28, model = "within")
summary(Reg_28a)

Reg_29a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_29, model = "within")
summary(Reg_29a)

Reg_30a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_30, model = "within")
summary(Reg_30a)

#Reg_31a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_31, model = "within")
#ummary(Reg_31a)

Reg_32a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_32, model = "within")
summary(Reg_32a)

#Reg_33a<- plm(Ri ~ Si + Pi + Net.sales, data = pnl_33, model = "within")
#summary(Reg_33a)
```


```{r}
###Group 1
stargazer::stargazer(Reg_10a, Reg_11a, Reg_12a, Reg_13a, Reg_14a, Reg_16a, Reg_17a, type = "text")

###Group 2
stargazer::stargazer(Reg_18a, Reg_20a, Reg_21a, Reg_22a, Reg_23a, Reg_24a, Reg_25a, type = "text")

###Group 3
stargazer::stargazer(Reg_26a, Reg_27a, Reg_28a, Reg_29a, Reg_30a, Reg_32a, type = "text")
```




```{r}
###NIC Tobit 
Reg_10b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_10)
summary(Reg_10b)

Reg_11b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_11)
summary(Reg_11b)

#Reg_12b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_12) {NO Cens term}
#summary(Reg_12b)

Reg_13b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_13)
summary(Reg_13b)

Reg_14b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_14)
summary(Reg_14b)

#Reg_15b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_15) {NO Cens term}
#summary(Reg_15b)


#Reg_16b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_16) {NO Cens term}
#summary(Reg_16b)

#Reg_17b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_17) {NO Cens term}
#summary(Reg_17b)

#Reg_18b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_18) {NO Cens term}
#summary(Reg_18b)

Reg_19b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_19)
summary(Reg_19b)

Reg_20b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_20)
summary(Reg_20b)

Reg_21b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_21)
summary(Reg_21b)

Reg_22b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_22)
summary(Reg_22b)

Reg_23b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_23)
summary(Reg_23b)

Reg_24b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_24)
summary(Reg_24b)

Reg_25b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_25)
summary(Reg_25b)

Reg_26b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_26)
summary(Reg_26b)

Reg_27b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_27)
summary(Reg_27b)

Reg_28b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_27)
summary(Reg_28b)

Reg_29b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_27)
summary(Reg_29b)

Reg_30b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_27)
summary(Reg_30b)

Reg_31b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_27)
summary(Reg_31b)

Reg_32b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_27)
summary(Reg_32b)

Reg_33b<- censReg(Ri ~ Si + Pi + Net.sales, data = pnl_27)
summary(Reg_33b)
```


```{r}
###Group 1
stargazer::stargazer(Reg_10b, Reg_11b, Reg_13b, Reg_14b, Reg_19b, type = "text")

###Group 2
stargazer::stargazer(Reg_20b, Reg_21b, Reg_22b, Reg_23b, Reg_24b, Reg_25b, type = "text")

###Group 3
stargazer::stargazer(Reg_26b, Reg_27b, Reg_28b, Reg_29b, Reg_30b, Reg_32b, type = "text")
```

```{r}
#NIC Gorups || Fixed effect model
G1<- plm(Ri ~ Si + Pi + Net.sales, data = G1, model = "within")
summary(G1)

G2<- plm(Ri ~ Si + Pi + Net.sales, data = G2, model = "within")
summary(G2)

G3<- plm(Ri ~ Si + Pi + Net.sales, data = G3, model = "within")
summary(G3)

G4<- plm(Ri ~ Si + Pi + Net.sales, data = G4, model = "within")
summary(G4)

G5<- plm(Ri ~ Si + Pi + Net.sales, data = G5, model = "within")
summary(G5)

G6<- plm(Ri ~ Si + Pi + Net.sales, data = G6, model = "within")
summary(G6)

G7<- plm(Ri ~ Si + Pi + Net.sales, data = G7, model = "within")
summary(G7)

G8<- plm(Ri ~ Si + Pi + Net.sales, data = G8, model = "within")
summary(G8)
```





